# Generated by Django 6.1.1 on 2026-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('course_number', models.CharField(max_length=5)),
                ('title', models.TextField()),
                ('credits', models.IntegerField(max_length=20)),
            ],
        ),
    ]
